### PR TITLE
Add overwrite checkbox to file upload

### PR DESCRIPTION
**Pull request by erikkemperman**

### CODE REVIEW

**Comment by jecollins** [comment]
I pulled in this PR and attempted to re-upload 2week-game.props through the files tab. I don't see an "upload" option in the games tab any more.

Not only does it fail, but I am getting an error message at the bottom of the browser window "Error: error.internalServerError (500 )". Also, the error dialog is off the bottom of the screen, and so I did not notice it the first couple times I tried it. No "overwrite" checkbox is shown.

I see no error messages in files/system/log.

**Comment by erikkemperman** [comment]
I am running this branch now and it appears to work fine...

screen shot 2017-03-02 at 20 14 44


Just to check though I tried a regular (non-incognito) browser that I had open on a previous version and even after F5/refresh I got stale code; no overwrite checkbox.

Were you in an incognito  window when you tried this, so you can be sure to not get cached content? As I mentioned, running in "dev" profile doesn't concatenate resources in a single file with (anti-cache) hash in their filenames, as it does in "prod".

About the success/error notifications -- I haven't had them fall off the screen but perhaps my screen is just taller. Also, they pile up a lot more now that I've doubled their on-screen time (because you mentioned not being able to copy/paste).


Should they be a the top? I found that annoying because the regular elements would then bounce up and down, and I'd often click the wrong one because of it.

**Comment by jecollins** [comment]
Very strange. Even stranger - when I opened an incognito window and logged in as admin, the files window was empty, until I uploaded a file, after which I could see all the logs, boot records, and config files. I guess I'll push this PR, but it still seems a bit flaky.

**Comment by erikkemperman** [comment]
This likely has to do with the file-system sync now in place, I recently reduced its interval to 5 seconds, but at-start up I gave it 10, to be sure that the (asynchronous) spring-boot initialization gets done first:
https://github.com/powertac/visualizer2/blob/master/src/main/java/org/powertac/visualizer/service_ptac/SyncFilesService.java#L43

**Comment by jecollins** [comment]
After processing PR20, I tried overwriting a game ID in a sim session. The game ran OK, but the logfiles are nowhere to be found. The originals were removed, and no new logs were written.

**Comment by erikkemperman** [comment]
I don't believe it is related to this PR, but I have just confirmed that overwriting sim session in server-distribution leaves no logs. It works fine for boot sessions. And when running from visualizer2 directory, overwriting boot sessions and sim sessions both work fine.

I will try to free up some time today to try and figure this out, at the moment I have no clue.

**Comment by erikkemperman** [comment]
It looks like it's running afoul of foreign key constraints, throwing away state/trace files that are still referenced by game entries. It did not do this before the dependency upgrade (and associated database patch), and I think it might only enforce these in production profile. To resolve this I guess I have to re-order database operations.

Unfortunately I'm out of time for today and have obligations all day tomorrow and most of Sunday... Will get back to this on Sunday evening.

**Comment by jecollins** [comment]
I've created issue #914 so we don't forget. This needs to be fixed, but PR19 is closed. Let's move the discussion to the issue.

**Pull request merged**
