### PR TITLE
Add .props suffix for configuration files, increase sync frequency

### PR DESCRIPTION
**Pull request by erikkemperman**

### CODE REVIEW

**Comment by jecollins** [comment]
If we cannot allow arbitrarily-named configuration files, then the README files in both visualizer2 and in server-distribution need to make the naming restrictions clear.

**Comment by jecollins** [comment]
Test game threw an error from viz:

205836 ERROR service_ptac.MessageHandler: Incoming spec 200000556 not matched in repo

I looked at this tariff spec, and it seems fine. It's a tariff that supersedes tariff 200000026. It gets published, offered, customers subscribe to it, and transactions are issued against it. The error occurs in the timeslot following the arrival of the spec.

**Comment by erikkemperman** [comment]
About the "not matched in repo" error, this has been happening for a while now. I emailed you about it at the time I first noticed it, a fairly long description was in an email on Sept. 17th, 2016,  with subject "Incoming spec X not matched in repo".

I don't think it is related to this PR?

**Comment by jecollins** [comment]
OK I see that. It's Issue #894.

**Pull request merged**
